#!/bin/sh

# Pre-installation shell script for Debian package

USER=pi
WORKSPACE=/home/$USER/jupyter/workspace
SYNADIR=$WORKSPACE/Synaptics

# Uninstall WebDS extensions
pip3 freeze | grep webds | xargs sudo pip3 uninstall -y

sudo rm -fr $SYNADIR

# Set up Synaptics directory within JupyterLab workspace
if [ ! -d "$SYNADIR" ]; then
  sudo mkdir -p $SYNADIR/Documentation/Specifications/TouchComm_Protocol
  sudo mkdir -p $SYNADIR/Documentation/User_Guides/AsicProgrammer
  sudo mkdir -p $SYNADIR/Documentation/User_Guides/TouchComm
  sudo mkdir -p $SYNADIR/Sample_Code
  sudo mkdir -p $SYNADIR/_links
  sudo chmod -R 755 $SYNADIR
  sudo install -d -o $USER -g $USER $SYNADIR/.ipynb_checkpoints
  sudo install -d -o $USER -g $USER $SYNADIR/Documentation/Specifications/TouchComm_Protocol/.ipynb_checkpoints
  sudo install -d -o $USER -g $USER $SYNADIR/Documentation/User_Guides/AsicProgrammer/.ipynb_checkpoints
  sudo install -d -o $USER -g $USER $SYNADIR/Documentation/User_Guides/TouchComm/.ipynb_checkpoints
  sudo install -d -o $USER -g $USER $SYNADIR/Sample_Code/.ipynb_checkpoints
  sudo install -d -o $USER -g $USER $SYNADIR/_links/.ipynb_checkpoints
fi
