#!/bin/sh

# Pre-installation shell script for Debian package

USER=dsdkuser
WORKSPACE=/home/$USER/jupyter/workspace
SYNADIR=$WORKSPACE/Synaptics
PACKRATDIR=$WORKSPACE/Packrat
STASHDIR=/var/spool/syna/data_collection/testrail

SYSTEMD=/etc/systemd/system/multi-user.target.wants
SERVICE=webds.service

# Stop and disable WebDS service
if [ -f $SYSTEMD/$SERVICE ]; then
  systemctl is-active $SERVICE > /dev/null 2>&1 && sudo systemctl stop $SERVICE
  sudo systemctl disable $SERVICE
fi

# Uninstall WebDS extensions
pip3 freeze | grep webds | xargs -r sudo pip3 uninstall -y

sudo rm -fr $WORKSPACE/packrat

# Set up Packrat directory within JupyterLab workspace
if [ ! -d "$PACKRATDIR" ]; then
  sudo install -d -o $USER -g $USER $PACKRATDIR
fi

sudo rm -fr $SYNADIR

# Set up Synaptics directory within JupyterLab workspace
if [ ! -d "$SYNADIR" ]; then
  sudo mkdir -p $SYNADIR/Documentation/Specifications/TouchComm_Protocol
  sudo mkdir -p $SYNADIR/Documentation/User_Guides/AsicProgrammer
  sudo mkdir -p $SYNADIR/Documentation/User_Guides/TouchComm
  sudo mkdir -p $SYNADIR/Documentation/WebDS_API
  sudo mkdir -p $SYNADIR/Sample_Code
  sudo mkdir -p $SYNADIR/Sample_Code/Carme_Gear_Selection
  sudo mkdir -p $SYNADIR/_links
  sudo chmod -R 755 $SYNADIR
  sudo install -d -o $USER -g $USER $SYNADIR/.ipynb_checkpoints
  sudo install -d -o $USER -g $USER $SYNADIR/Documentation/Specifications/TouchComm_Protocol/.ipynb_checkpoints
  sudo install -d -o $USER -g $USER $SYNADIR/Documentation/User_Guides/AsicProgrammer/.ipynb_checkpoints
  sudo install -d -o $USER -g $USER $SYNADIR/Documentation/User_Guides/TouchComm/.ipynb_checkpoints
  sudo install -d -o $USER -g $USER $SYNADIR/Documentation/WebDS_API/.ipynb_checkpoints
  sudo install -d -o $USER -g $USER $SYNADIR/Sample_Code/.ipynb_checkpoints
  sudo install -d -o $USER -g $USER $SYNADIR/Sample_Code/Carme_Gear_Selection/.ipynb_checkpoints
  sudo install -d -o $USER -g $USER $SYNADIR/_links/.ipynb_checkpoints
fi

# Set up data collection stash directory
if [ ! -d "$STASHDIR" ]; then
  sudo mkdir -p $STASHDIR
fi

# Stop and disable systemd-timesyncd service
systemctl is-active systemd-timesyncd > /dev/null 2>&1 && sudo systemctl stop systemd-timesyncd
sudo systemctl disable systemd-timesyncd
