#!/bin/sh

# Pre-removal shell script for Debian package

SYSTEMD=/etc/systemd/system
SERVICE=jupyterlab.service

# Uninstall WebDS extensions
pip3 freeze | grep webds | xargs -r sudo pip3 uninstall -y

if [ -f $SYSTEMD/$SERVICE ]; then
  systemctl is-active $SERVICE > /dev/null 2>&1 && sudo systemctl restart $SERVICE
fi
