#!/bin/sh

# Pre-removal shell script for Debian package

SYSTEMD=/etc/systemd/system/multi-user.target.wants
SERVICE=webds.service

# Uninstall WebDS extensions
pip3 freeze | grep webds | xargs -r sudo pip3 uninstall -y

# Stop and disable WebDS service
if [ -f $SYSTEMD/$SERVICE ]; then
  systemctl is-active $SERVICE > /dev/null 2>&1 && sudo systemctl stop $SERVICE
  sudo systemctl disable $SERVICE
fi

if [ -f $SYSTEMD/jupyterlab.service ]; then
  systemctl is-active jupyterlab.service > /dev/null 2>&1 && sudo systemctl restart jupyterlab.service
fi
